application: smart-relay
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
- url: /bootstrap
  static_dir: lib/bootstrap-3.3.4-dist
- url: /css
  static_dir: templates/css
- url: /js
  static_dir: templates/js
- url: /control
	login: required
- url: .*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
